version: "2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
    - 2181:2181
    logging:
      driver: none

  kafka:
    image: confluentinc/cp-kafka:3.2.0
    ports:
    - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: plaintext://kafka:9092
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_JMX_PORT: 9010
    logging:
      driver: none
    depends_on: [zookeeper]

  influx:
    image: influx
    ports:
    - 8086:8086

  kandi:
    build:
      context: .
      dockerfile: ./etc/dev/Dockerfile.dev
    ports:
    - 8089:8089
    - 8090:8090
    environment:
    - KANDI_kandi.batch.max=10
    - KANDI_kandi.batch.initial=1
    - KANDI_kandi.batch.reset=600
    - KANDI_influx.url=http://influx:8086
    - KANDI_influx.user=myuser
    - KANDI_influx.password=mypwd
    - KANDI_influx.timeout=35
    - KANDI_influx.database=test
    - KANDI_influx.retentionPolicy=autogen
    - KANDI_influx.writeConsistency=any
    - KANDI_kafka.brokers=kafka:9092
    - KANDI_kafka.topics=test-influx-metrics
    - KANDI_kafka.consumerGroup=test
    - KANDI_kafka.loggingEnabled=true
    - KANDI_kafka.consumer.offsets.initial=newest
    - KANDI_kafka.consumer.return.errors=true
    - KANDI_kafka.version=0.10.1.1
    - KANDI_kafka.clientID=test-client-id
    - KANDI_kafka.channelBufferSize=17
    - KANDI_kafka.group.return.notifications=true
    - KANDI_kafka.group.partitionStrategy=roundrobin
    - KANDI_kafka.group.heartbeat.interval=3
    - KANDI_kafka.group.session.timeout=90
    depends_on:
      - kafka
      - telegraf

  telegraf:
    image: quay.io/nordstrom/telegraf:1.3.0-1
    volumes:
    - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influx