influx:
  Url: my-test-url:8082
  User: fred
  Password: fredspassword
  Timeout: 1
  UserAgent: meh
  Database: test-db
  Precision: test-precision
  RetentionPolicy: mypolicy
  WriteConsistency: anywrite

kandi:
  backoff:
    max: 1
    interval: 2
    reset: 3
  batch:
    size: 4
    duration: 5

kafka:
  brokers: test-url:9092
  topics: test-topics
  consumerGroup: test-consumer-group
  loggingEnabled: true
  consumer:
    offsets:
      initial: newest
      retention: 1
      commitInterval: 2
    return:
      errors: true
    retry:
      backoff: 3
    maxWaitTime: 4
    maxProcessingTime: 5
    fetch:
      max: 6
      min: 7
      default: 8
  metadata:
    retry:
      max: 9
      backoff: 10
    refreshFrequency: 11
  version: 4-4-4-4
  net:
    writeTimeout: 12
    keepAlive: 13
    maxOpenRequests: 14
    readTimeout: 15
    dialTimeout: 16
  clientID: test-client-id
  group:
    return:
      notifications: true
    offsets:
      retry:
        max: 18
    partitionStrategy: range
    heartbeat:
      interval: 19
    session:
      timeout: 20